mulesoft/mule-wsc-connector

src/main/java/org/mule/extension/ws/api/WebServiceSecurity.java
=> MULE-12608: Remove com.google.common from exported packages

pom.xml
=> MULE-12609: Every exported Mule package must contain api

src/main/java/org/mule/extension/ws/api/WebServiceSecurity.java
_ Moving classes out of core's api package
_ When possible, classes where moved to internal
_ Moved to privileged when classes where required on compatibility
_ Moved to other module's API when needed on tests or it made sense
_ Deleted if not needed anymore
_ Some tests were ignored as they use an internal class and need refactoring
=> MULE-13545: Cleanup core API

pom.xml
Reverts mulesoft/mule-wsc-connector#63
=> Revert "Update MuleCoreModulesParent to version 1.0.0"

pom.xml
=> MULE-14671: MuleApplicationClassloader is leaked when through SOAP

src/main/java/org/mule/extension/ws/internal/transport/ExtensionsClientHttpRequestExecutor.java, src/test/java/org/mule/extension/ws/SoapTestXmlValues.java, src/test/java/org/mule/extension/ws/runtime/EchoTestCase.java, src/test/java/org/mule/extension/ws/runtime/WscConnectionTestCase.java, src/test/java/org/mule/extension/ws/runtime/transport/DefaultHttpConfigTestCase.java, src/test/java/org/mule/extension/ws/runtime/transport/HttpBasicAuthConfigTestCase.java, src/test/java/org/mule/extension/ws/runtime/transport/SimpleHttpConfigTestCase.java, src/test/java/org/mule/extension/ws/runtime/wss/AbstractWebServiceSecurityTestCase.java, src/test/java/org/mule/extension/ws/runtime/wss/WssTimestampTestCase.java
CompositeProcessorChainRouter
Just being a good citizen here
=> MULE-16221: HTTP:CONNECTIVITY error thrown from WSC hangs execution in

src/main/java/org/mule/extension/ws/api/SoapAttributes.java, src/main/java/org/mule/extension/ws/api/transport/CustomHttpTransportConfiguration.java, src/main/java/org/mule/extension/ws/api/transport/HttpRequestResponse.java, src/main/java/org/mule/extension/ws/internal/ConsumeOperation.java, src/main/java/org/mule/extension/ws/internal/WebServiceConsumer.java, src/main/java/org/mule/extension/ws/internal/connection/DefaultHttpMessageDispatcher.java, src/main/java/org/mule/extension/ws/internal/transport/ExtensionsClientHttpRequestExecutor.java, src/main/java/org/mule/extension/ws/internal/transport/HttpResourceLocator.java, src/test/java/org/mule/extension/ws/SoapAttributesTestCase.java, src/test/java/org/mule/extension/ws/SoapOutputEnvelopeTestCase.java, src/test/java/org/mule/extension/ws/metadata/OutputMetadataTestCase.java
https://www.mulesoft.org/jira/browse/MULE-16407
=> MULE-16333: Web Service Consumer does not expose HTTP status code

pom.xml
If merged, this commit updates the soap engine version from 1.1.2 to 1.1.3-SNAPSHOT
=> MULE-16970: update soap engine version

pom.xml, src/main/java/org/mule/extension/ws/api/WebServiceSecurity.java, src/main/java/org/mule/extension/ws/api/security/WssIncomingTimestampSecurityStrategyAdapter.java, src/test/munit/wss/incoming-timestamp-test-case.xml, src/test/munit/wss/timestamp-test-case.xml, src/test/munit/wss/timestamp-verification-test-case.xml, src/test/resources/soapui-prj/simple-service-soap12-soapui-project.xml, src/test/resources/soapui-prj/simple-service-soapui-project.xml
=> MULE-17106: Timestamp on response not being processed

pom.xml
If merged, this commit updates the wsdl parser from 1.4.0-SNAPSHOT to 1.3.0
and soap engine from 1.2.0-SNAPSHOT to 1.2.0
=> Update wsdl parser and soap engine

pom.xml, src/test/resources/JenkinsfileDockerWindows
- Adding pipeline for publishing Windows-based IBM MQ Docker image to
the internal registry
=> EE-6739: Upload Windows Docker Images used in tests to Mulesoft Docker repository

pom.xml
- Adjusting the project within Harbor where runtime images are pushed to
=> EE-6894: Fix issue pushing Docker images to Harbor

pom.xml
* Also, piggyback fix of WARNINGS in poms
=> MULE-18023: Remove spring repo declaration in poms

pom.xml, src/main/java/org/mule/extension/ws/internal/ConsumeOperation.java, src/main/java/org/mule/extension/ws/internal/SoapMessageBuilder.java, src/test/munit/echo-test-case.xml, src/test/resources/soapui-prj/simple-service-soap12-soapui-project.xml, src/test/resources/soapui-prj/simple-service-soapui-project.xml
It won't build until mule-soap-engine's new version is released (https://github.com/mulesoft/mule-soap-engine/pull/125).
=> fix/WSCC 72: Enable option to append XML initial tag into body

pom.xml, src/main/java/org/mule/extension/ws/api/SoapAttributes.java, src/main/java/org/mule/extension/ws/api/addressing/AddressingAttributes.java, src/main/java/org/mule/extension/ws/api/addressing/AddressingConfiguration.java, src/main/java/org/mule/extension/ws/api/addressing/AddressingSettings.java, src/main/java/org/mule/extension/ws/api/addressing/AddressingVersion.java, src/main/java/org/mule/extension/ws/api/reliablemessaging/ReliableMessagingConfiguration.java, src/main/java/org/mule/extension/ws/api/reliablemessaging/ReliableMessagingConnectionSettings.java, src/main/java/org/mule/extension/ws/api/reliablemessaging/ReliableMessagingSettings.java, src/main/java/org/mule/extension/ws/internal/ParseResponseOperation.java, src/main/java/org/mule/extension/ws/internal/ReliableMessagingOperations.java, src/main/java/org/mule/extension/ws/internal/WebServiceConsumer.java, src/main/java/org/mule/extension/ws/internal/addressing/properties/AddressingPropertiesImpl.java, src/main/java/org/mule/extension/ws/internal/addressing/value/AddressingActionValueProvider.java, src/main/java/org/mule/extension/ws/internal/addressing/value/AddressingToValueProvider.java, src/main/java/org/mule/extension/ws/internal/error/CreateRMSequenceErrorTypeProvider.java, src/main/java/org/mule/extension/ws/internal/error/ParseResponseErrorTypeProvider.java, src/main/java/org/mule/extension/ws/internal/error/TerminateRMSequenceErrorTypeProvider.java, src/main/java/org/mule/extension/ws/internal/metadata/AbstractOutputResolver.java, src/main/java/org/mule/extension/ws/internal/metadata/ParseResponseOutputResolver.java, src/main/java/org/mule/extension/ws/internal/reliablemessaging/ReliableMessagingPropertiesImpl.java, src/main/java/org/mule/extension/ws/internal/reliablemessaging/value/ReliableMessagingVersionValueProvider.java, src/main/java/org/mule/extension/ws/internal/util/Path.java, src/main/java/org/mule/extension/ws/internal/util/PathUtils.java
=> WSCC-91: Change feature version

pom.xml
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
=> Update munit.version to v2.3.1 (#256)

pom.xml, src/test/munit/mtom/mtom-and-signature-verification-test-case.xml
cherrypicks + wsdl parser + soap-engine
=> 1.6.2 cherrypicks

renovate.json
renovate settings for ignoring monthly builds
=> WSCC-105: renovate settings for ignoring monthly builds

pom.xml
This reverts commit 807a81b0cc2032cc257e3a78732480565457fc89.
=> Revert "Update dependency io.fabric8:docker-maven-plugin to v0.40.2"

pom.xml
=> W-13064379: Release/patch-1.8.2

pom.xml
=> W-13971847-Update dependencies

pom.xml
=> W-13971847-Release_1.8.3

src/main/java/org/mule/extension/ws/api/transport/DefaultHttpTransportConfiguration.java
…portConfiguration timeout (#467)
* Add summary and alias for DefaultHttpTransportConfiguration timeout
* Replace alias with display name
(cherry picked from commit 6d224e74d1b3f5aee73878240b40bab7171ef35a)
=> W-14651658 | Add summary and change display name for DefaultHttpTransportConfiguration timeout

pom.xml
=> W-14606069: Remove snapshot
